### ISSUE TITLE
Default precision value in __pazcal_write

### ISSUE THREAD

**Issue by tdiam** [softlab-ntua/pazcal#3]
**In** `include/pazcal`:

``` c++
inline void __pazcal_write_fmt (double a, int w, int p)
{
  printf("%*.*lf", w, p, a);
}
...
template<typename T>
inline void __pazcal_write (T const& a)
{
  __pazcal_write_fmt(a, 0, 0);
}
```

This sets the default precision of printf to zero.
Therefore all floats and doubles (thus, REALs too) are printed as integers.

**Minimal working example**:

```
PROGRAM test() {
    REAL a = 3.14;
    WRITELN(a);
}
```

**Output**:

```
3
```

**Suggested fix**:
Change passed arguments of __pazcal_write_fmt to `__pazcal_write_fmt(a, 0, 6);` wherever needed.

**Comment by nickie** [comment]
Κάνε όμως ένα merge request, να μπεις κι εσύ στο hall of fame, να γλυτώσω κι εγώ το ψάξιμο...  Thanks Θοδωρή... :-)
